### ISSUE TITLE
./build/bin/main -m /PATH/TO/MODEL -n $output_token_count -t $thread_num -p $prompt '.' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by 18635191739** [SJTU-IPADS/PowerInfer#101]
我的build文件夹下没有bin文件夹是什么问题？请大神指导

**Comment by 18635191739** [comment]
我是在Windows下编译的。支持windows编译吗

**Comment by hodlen** [comment]
目前Windows的支持仍然在进行中，在主线分支上的代码无法编译是正常的。请关注 #86 的进展。

---

Currently, support for Windows is still in progress, and it's normal for the code in the main branch to not compile yet. Please follow the progress on issue #86.
