### ISSUE TITLE
01-ai的Yi模型系列可以适配吗，我看模型结构是跟llama一样的

### ISSUE THREAD

**Issue by felixstander** [SJTU-IPADS/PowerInfer#102]
# Prerequisites

Before submitting your question, please ensure the following:

- [ ] I am running the latest version of PowerInfer. Development is rapid, and as of now, there are no tagged versions.
- [ ] I have carefully read and followed the instructions in the [README.md](https://github.com/SJTU-IPADS/PowerInfer/blob/main/README.md).
- [ ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).

# Question Details

Please provide a clear and concise description of your question. If applicable, include steps to reproduce the issue or behaviors you've observed.

# Additional Context

Please provide any additional information that may be relevant to your question, such as specific system configurations, environment details, or any other context that could be helpful in addressing your inquiry.

**Comment by hodlen** [comment]
感谢你的关注。目前 PowerInfer 暂不支持 Yi 模型，我们只支持基于 ReLU 的模型。

请参考我们的 [FAQs](https://github.com/SJTU-IPADS/PowerInfer#faqs) 以及先前issue中的讨论，包括但不限于以下链接：

* #56 
* #32 
* #17 

同时，我们对 Fine-tune Yi 模型非常感兴趣，正在积极与 01-ai 取得联系。希望能在适当的时候公布我们的进展。请保持关注！

---

Thanks for your interest. We only support ReLU-based models for now, and Yi has not yet been supported. 

Please kindly refer to our [FAQs](https://github.com/SJTU-IPADS/PowerInfer#faqs) and discussions from previous issues, including:

* #56 
* #32 
* #17 

Additionally, we are very interested in fine-tuning the Yi model and are actively in contact with 01-ai. We hope to announce our progress at an appropriate time. Please stay tuned!
