### ISSUE TITLE
Windows Visual Studio编译失败

### ISSUE THREAD

**Issue by dyt06** [SJTU-IPADS/PowerInfer#107]
严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
消息	lnt-uninitialized-local	未初始化本地变量。	main.exe (bin\main.exe)	E:\PowerInfer\examples\main\main.cpp	172		
消息	lnt-uninitialized-local	未初始化本地变量。	main.exe (bin\main.exe)	E:\PowerInfer\examples\main\main.cpp	173		

    llama_model * model;
    llama_context * ctx;

**Comment by hodlen** [comment]
目前Windows平台编译支持尚未完成，请关注 #86 的进展。请参考相关issue: #58, #49。
---
We are fixing issues on Windows compiling, please stay tuned for #86 and kindly refer to related issues: #58, #49.
