### ISSUE TITLE
will it run on windows ?

### ISSUE THREAD

**Issue by Sandy4321** [SJTU-IPADS/PowerInfer#115]
# Prerequisites

Before submitting your question, please ensure the following:

- [x ] I am running the latest version of PowerInfer. Development is rapid, and as of now, there are no tagged versions.
- [x ] I have carefully read and followed the instructions in the [README.md](https://github.com/SJTU-IPADS/PowerInfer/blob/main/README.md).
- [x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).

# Question Details

will it run on windows ?

# Additional Context

i use windows 10 , no gpu, 150GB ram

**Comment by hodlen** [comment]
We are actively developing Windows support. Please keep an eye on issue #86 for updates. As of now, CPU inference support is available in PR #114. 

Although this feature is still in the experimental phase, we welcome you to give it a try.

**Comment by Sandy4321** [comment]
pls do it asap
