### ISSUE TITLE
How to acquire predictor weights

### ISSUE THREAD

**Issue by fakerybakery** [SJTU-IPADS/PowerInfer#135]
Hi,
I'm a beginner in this space. I'm interested in converting my custom model to the PowerInfer GGUF format, and I saw I need predictor weights to convert it. Do you know how I can acquire these for a custom model?
Thanks!

**Comment by hodlen** [comment]
Welcome, @fakerybakery ! We are currently limited to a short list of models, as stated in our [FAQs](https://github.com/SJTU-IPADS/PowerInfer#faqs), but we are progressing in #93 to support more model architectures.

If you are interested in how to train the predictor weights for a model with supported architecture, please kindly refer to #116, #84, #83.

**Comment by fakerybakery** [comment]
Thank you so much! Sorry about the duplicate!
