### ISSUE TITLE
CMake 3.17 or higher is required. The repository asks for version 3.13.4

### ISSUE THREAD

**Issue by Rubiel1** [SJTU-IPADS/PowerInfer#144]
# Prerequisites

Before submitting your issue, please ensure the following:

- [ X] I am running the latest version of PowerInfer. Development is rapid, and as of now, there are no tagged versions.
- [ X] I have carefully read and followed the instructions in the [README.md](https://github.com/SJTU-IPADS/PowerInfer/blob/main/README.md).
- [ X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).

# Expected Behavior
 Build PowerInfer

Please provide a detailed written description of what you were trying to do, and what you expected PowerInfer to do.

1.- I run the line """PowerInfer]$ cmake -S . -B build -DLLAMA_CUBLAS=ON""" and I was expected PowerInfer to be build.

# Current Behavior      

Please provide a detailed written description of what PowerInfer did, instead.
 
I received the output: """CMake Error at CMakeLists.txt:252 (cmake_minimum_required):
  CMake 3.17 or higher is required.  You are running version 3.13.4
"""
 
But the github repository asks for CMake 3.13+

# Failure Information (for bugs)

Please help provide information about the failure / bug.

It asks me for CMake 3.17  when the github repository asks for CMake 3.13.

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. step 1 Open  [CMakeList.txt](https://github.com/SJTU-IPADS/PowerInfer/blob/52ff38f963c1dbb924660909e27793d6796d13c3/CMakeLists.txt#L252)
2. step 2 Go to line 252
3. step 3 "if (LLAMA_CUBLAS)
    cmake_minimum_required(VERSION 3.17)"

**Comment by hodlen** [comment]
Thank you for bringing this discrepancy to our attention. We will update our documentation to match the correct CMake version requirement ASAP.
