### ISSUE TITLE
The quesion about multiple GPu

### ISSUE THREAD

**Issue by YuMJie** [SJTU-IPADS/PowerInfer#152]
When I run the code I see that it has one main GPU being fully utilized while the other GPU is being used very little. Why is this so.? Can I take full advantage of all GPUs?

**Comment by YuMJie** [comment]
Thank for your help. But it exists a question why the other GPUs will be used.
![image](https://github.com/SJTU-IPADS/PowerInfer/assets/64304120/529f9000-9ed1-41d2-bfa3-8db18d2c5274)

**Comment by hodlen** [comment]
llama.cpp has tensor split feature so in this case attention layers can distribute to multiple GPUs but none of the FFNs.

**Comment by YuMJie** [comment]
Thank you for your reply and help!
