### ISSUE TITLE
The quesion about Neuron-aware Operator

### ISSUE THREAD

**Issue by YuMJie** [SJTU-IPADS/PowerInfer#154]
Thank you for your great job! I see you introduce the  Neuron-aware Operator during inference.
However I can not find the code about Neuron-aware Operator and where they are used.

Additional question:
```    // FFN up
    third = cur;
    struct ggml_tensor * tmp = ggml_mul_mat_idx(ctx, up, cur, idx, gpu_index);
    cb(tmp, "ffn_up_sparse", il);
#ifdef GGML_USE_CUBLAS
    struct ggml_tensor * tmp2 = ggml_mul_mat_special(ctx, up_gpu, cur, idx, gpu_bucket, up);
    if (tmp2 != NULL) {
        ggml_cuda_assign_buffers_no_alloc(tmp2);
        cb(tmp2, "ffn_up_sparse_gpu", il);
    }
    tmp = ggml_add(ctx, tmp, tmp2);
#endif
    if (up_b) {
        tmp = ggml_add(ctx, tmp, up_b);
        cb(tmp, "ffn_up_b", il);
    }

I am confused that ifdef GGML_USE_CUBLAS=0 ,the result may be different because it uses the additional mut and add operations.

**Comment by Yues007** [comment]
Could you please inform me if you have identified the location of the operator within the code? If so, I would greatly appreciate your assistance in sharing that information. Thank you!

**Comment by Yues007** [comment]
@YuMJie

**Comment by YuMJie** [comment]
@Yues007 
I think  the CPU neuron-aware operator is in https://github.com/SJTU-IPADS/PowerInfer/blob/6ae7e06dbe1032ec103e1a08ce126b3d1ed2d6e7/ggml.c#L14030
and the GPU neuron-aware operator is in https://github.com/SJTU-IPADS/PowerInfer/blob/6ae7e06dbe1032ec103e1a08ce126b3d1ed2d6e7/ggml-cuda.cu#L8787
