### ISSUE TITLE
Which A100 are you guys using?

### ISSUE THREAD

**Issue by homosapien-lcy** [SJTU-IPADS/PowerInfer#16]
Thanks for the great work!
Just curious, in "Evaluation shows that PowerInfer attains an average token generation rate of 13.20 tokens/s, with a peak of 29.08 tokens/s, across various LLMs (including OPT-175B) on a single NVIDIA RTX 4090 GPU, only 18% lower than that achieved by a top-tier server-grade A100 GPU. This significantly outperforms llama.cpp by up to 11.69x while retaining model accuracy."
Are you guys talking about the 40GB version of A100 or the 80GB version?

**Comment by YixinSong-e** [comment]
Thank you for your interest! We use nvidia a100-sxm4-80gb for comparison in our paper.
