### ISSUE TITLE
Does PowerInfer support multi-GPU?

### ISSUE THREAD

**Issue by LHQUer** [SJTU-IPADS/PowerInfer#163]
# Prerequisites

Before submitting your question, please ensure the following:

- [ ] I am running the latest version of PowerInfer. Development is rapid, and as of now, there are no tagged versions.
- [ ] I have carefully read and followed the instructions in the [README.md](https://github.com/SJTU-IPADS/PowerInfer/blob/main/README.md).
- [ ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).

# Question Details

Does PowerInfer support multi-GPU? I run this project on machine with 8 RTX3090, but I find that only one gpu was used during the Inference task.

# Additional Context

Please provide any additional information that may be relevant to your question, such as specific system configurations, environment details, or any other context that could be helpful in addressing your inquiry.

**Comment by hodlen** [comment]
Please kindly refer to #152
