### ISSUE TITLE
Does this support llama type models as well (Using SwiGLU activation)?

### ISSUE THREAD

**Issue by homosapien-lcy** [SJTU-IPADS/PowerInfer#17]
Without replacing the activation function?
Again, amazing work!!

**Comment by YixinSong-e** [comment]
We also hope to utilize sparse activation features in LLM using other activation functions, and are currently conducting related research. We also look forward to more research participating. :)

**Comment by homosapien-lcy** [comment]
> Currently we do not support. However, We also hope to utilize sparse activation features in LLM using other activation functions, and are currently conducting related research. We also eagerly anticipate more collaborations and contributions from the wider research community. :)

Thanks for the prompt reply! If this also works for other activation functions that will be great, since the drop in math performance (GSM8K https://huggingface.co/SparseLLM/ReluLLaMA-70B) seems to be quite big.

**Comment by YixinSong-e** [comment]
> > Currently we do not support. However, We also hope to utilize sparse activation features in LLM using other activation functions, and are currently conducting related research. We also eagerly anticipate more collaborations and contributions from the wider research community. :)
> 
> Thanks for the prompt reply! If this also works for other activation functions that will be great, since the drop in math performance (GSM8K https://huggingface.co/SparseLLM/ReluLLaMA-70B) seems to be quite big.

In fact, the decrease in mathematical indicators is mainly due to a lack of mathematical related corpus during finetuning, and the SparseLLM Team will continue to update this model in the future. :)

**Comment by RedBlazing** [comment]
> Without replacing the activation function? Again, amazing wor

Hello, I'm 18 just finding this through code files but what is this site
