### ISSUE TITLE
convert.py: error: the following arguments are required: mlp_model

### ISSUE THREAD

**Issue by wojiaoshihua** [SJTU-IPADS/PowerInfer#173]
When I tried to deploy llava with your outstanding work, I encountered an error：
usage: convert.py [-h] [--dump] [--dump-single] [--vocab-only] [--outtype {f32,f16,q8_0}] [--vocab-dir VOCAB_DIR]
                  [--outfile OUTFILE] [--ctx CTX] [--concurrency CONCURRENCY] [--bigendian] [--vocabtype {spm,bpe}]
                  model mlp_model
convert.py: error: the following arguments are required: mlp_model

How can I get the mlp_model

**Comment by hodlen** [comment]
`mlp_model` stands for the predictor weights as listed under this [section](https://github.com/SJTU-IPADS/PowerInfer#convert-from-original-model-weights--predictor-weights) of README. So far, there are no easy ways to train such predictors for popular LLMs like LLaVA, and please stay tuned to #93 for our further model rollouts.

**Comment by wojiaoshihua** [comment]
Thank you for your helpful reply，looking forward to your follow-up work!By the way, when I try to apply it in my model just like LLaVA, should I do something like your reply in #54 ?

**Comment by hodlen** [comment]
Exactly. If you'd like to train sparsity predictors for a model, you can follow the way of Deja Vu. However, you might find non-ReLU models are harder to predict and causes larger predictor/poorer accuracy. 

BTW we plan to roll out a framework to streamline this process, but there is no expected time yet.

**Comment by wojiaoshihua** [comment]
Thanks.
