### ISSUE TITLE
Quantized INT4/Q4 model?

### ISSUE THREAD

**Issue by JianbangZ** [SJTU-IPADS/PowerInfer#18]
How are the gguf weights quantized to INT4? is there a script similar to llama.cpp to convert to fp16 weigths to q4_0? 
Please share more details about INT4 model.

**Comment by YixinSong-e** [comment]
Our quantization script is aligned with llama.cpp, you can directly use it by `./build/bin/quantify -- pure $PATH_ TO_ ORIGIN_ MODEL $Q4_ MODEL_ NAME Q4_ 0`

**Comment by hodlen** [comment]
Thanks for your feedback! We have added model quantization under README: https://github.com/SJTU-IPADS/PowerInfer#quantization.
