### ISSUE TITLE
How to calculate the number of activated params in TurboSparse paper?

### ISSUE THREAD

**Issue by ustcwhy** [SJTU-IPADS/PowerInfer#195]
# Question Details

Thanks for your wonderful work [TurboSparse](https://arxiv.org/pdf/2406.05955). 

It is amazing to have only 2.5B activated params of Mistral-7B but achieve good performance.

However, I wonder how this number "2.5B" is calculated. I check the code released in [HF](https://huggingface.co/PowerInfer/TurboSparse-Mixtral-Instruct/blob/main/modeling_turbosparsemixtral.py). It seems that only the input of down proj of each GLU layer is sparsified. Even if the sparsity raio reaches 100%, the params of down proj only accounts for 2/9 of the model.

**Comment by YixinSong-e** [comment]
Thank you for your interest! 
Actually we consider the corresponding rows in the up and gate projections and the columns in the down projection as a single neuron. When the intermediate result after applying the activation function is zero, we regard the corresponding neurons in the up, gate, and down projections as inactive. For example, if the first element of the vector is zero after passing through the up, gate, and ReLU activation functions, we consider the first row weights in the up and gate projections, as well as the first column weights in the down projection, to be inactive.
If 90% intermediate element is zero, we regard only 10% params are activated in FFN.

**Comment by ustcwhy** [comment]
> Thank you for your interest! Actually we consider the corresponding rows in the up and gate projections and the columns in the down projection as a single neuron. When the intermediate result after applying the activation function is zero, we regard the corresponding neurons in the up, gate, and down projections as inactive. For example, if the first element of the vector is zero after passing through the up, gate, and ReLU activation functions, we consider the first row weights in the up and gate projections, as well as the first column weights in the down projection, to be inactive. Refers to DejaVu, PowerInfer that we can predict to skip rows in gate and up projection matrix.
> 
> If 90% intermediate element is zero, we regard only 10% params are activated in FFN.

Thanks for your comment! I get it.
