### ISSUE TITLE
支持的量化类型

### ISSUE THREAD

**Issue by deleteeeee** [SJTU-IPADS/PowerInfer#196]
![image](https://github.com/SJTU-IPADS/PowerInfer/assets/145892840/05840070-e6d3-4835-9741-732c1e45661b)
您好，请问一下，目前只支持F16和Q4_0这两种么，我在运行其它量化类型的的模型时会出现unsupported type

**Comment by Dujianhua1008** [comment]
？？？原来是这里的问题  我做了 Q8 Q4_k 跑起来都是 ###
