### ISSUE TITLE
代码中使用的llama.cpp版本

### ISSUE THREAD

**Issue by weizhenhuan** [SJTU-IPADS/PowerInfer#200]
Hi， 我想要知道Powerinfer源码使用的llama.cpp版本是多少，最好可以精确到commit号，这样我可以知道具体做了哪些改动。谢谢开发者。

**Comment by keaikeqing** [comment]
https://github.com/ggerganov/llama.cpp/tree/6bb4908a17150b49373b5f977685b2e180a04f6f
