### ISSUE TITLE
再结合上MLX岂不是可以在Mac平台起飞了！

### ISSUE THREAD

**Issue by learningpro** [SJTU-IPADS/PowerInfer#21]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

在Mac M系列平台上，是否可以进一步结合上https://github.com/ml-explore/mlx 从而达到更夸张的提速效果？

Please provide a detailed written description of what you were trying to do, and what you expected `llama.cpp` to do as an enhancement.

# Motivation

Please provide a detailed written description of reasons why this feature is necessary and how it is useful to `llama.cpp` users.

# Possible Implementation

If you have an idea as to how it can be implemented, please write a detailed description. Feel free to give links to external sources or share visuals that might be helpful to understand the details better.

**Comment by hodlen** [comment]
感谢关注！我们暂时没有支持MLX的计划，但是接下来我们将会支持Metal（GPU），我们预计会给M Chips带来可观的性能提升。
