### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by nd7141** [SJTU-IPADS/PowerInfer#27]
What the speedup means here? speedup compared to what? 

<img width="624" alt="image" src="https://github.com/SJTU-IPADS/PowerInfer/assets/4607709/49ccc41b-0ebe-4b05-b602-20dc6694bc23">

**Comment by YixinSong-e** [comment]
Thank you for your attention
The X axis indicates the output length.  The Y axis represents the speedup compared with llama.cpp. The number above each bar indicates the end-to-end generation speed (tokens/s).

**Comment by nd7141** [comment]
I'm still confused about Y axis, because if it's speed up compared to llamacpp, what orange bar is? I thought orange bar is llamacpp, so why it's not 1 all the time for orange bars?

**Comment by hodlen** [comment]
The graph is a bit complex indeed. The height of bars (Y axis) indicates speedup compared with llama.cpp, so all orange bars have a height of 1. Then, the numbers above all bars are the actual generation speed, so you can see the generation speed of llama.cpp above each orange bar.
