### ISSUE TITLE
Length 

### ISSUE THREAD

**Issue by cyzhh** [SJTU-IPADS/PowerInfer#35]
1. 我想问一下，是否有在Length 更长的情况下，比较性能，如果在A100上使用PowerInfer以及length=2048或者更高的情况下，是否能够起到类似文中的效果？ 
2. 另外还想问一下，是怎样一个想法致使你们会使用ReLU激活函数而不是遵从原来的SwiGLU？

**Comment by YixinSong-e** [comment]
感谢你的关注！
1. 我还没有试过，但是如果在A100上，我们也许可以将更多的KV cache放在GPU上，这样generation阶段的速度可以更好，我认为length目前的影响主要在于prompt phase，也就是生成第一个token的时间，随着一次 input length越来越长，prompt阶段的处理时间会很长，主要原因在于目前稀疏算子对于同时多个token并不够高效，我们会继续优化。
2. 我们工作的启发点在于以下关于大模型稀疏激活的工作：https://proceedings.mlr.press/v202/liu23am.html、https://arxiv.org/abs/2110.01786、https://openreview.net/forum?id=TJ2nxciYCk-、https://openreview.net/forum?id=osoWxY8q2E。 从这些paper我们得到了以下信息：1） ReLU LLM有明显的稀疏激活现象 2) 使用ReLU激活函数训练模型对于模型的性能影响不大 3) 其他激活函数上的稀疏性并没有得到很好的研究。 尽管现在很多LLM都是SwiGLU，但我们想先从稀疏激活的角度去思考看这能否带来更大的收益，如果有，我们也希望能有更多关于稀疏激活的研究工作参与进来。  :)

**Comment by cyzhh** [comment]
非常感谢你的回答！
