### ISSUE TITLE
server  cannot run

### ISSUE THREAD

**Issue by Gengchunsheng** [SJTU-IPADS/PowerInfer#53]
![server1](https://github.com/SJTU-IPADS/PowerInfer/assets/154514502/80343002-5ee0-4b1f-bd52-769f669fd8b1)

**Comment by jtoy** [comment]
I got it running for me on Linux with a 4090

**Comment by jtoy** [comment]
And what is required to test it? Do we just recompile or do we need to reconvert weights?

**Comment by hodlen** [comment]
If you encountered this issue in CPU-only inference, the bug should be fixed via #62. 
Please try to recompile at the latest main branch and give it another try. If the bug persists, please share your logs with us for troubleshooting. Thanks!

**Comment by Gengchunsheng** [comment]
> If you encountered this issue in CPU-only inference, the bug should be fixed via #62. Please try to recompile at the latest main branch and give it another try. If the bug persists, please share your logs with us for troubleshooting. Thanks!

Server can  run now after update the code.
![Image 9](https://github.com/SJTU-IPADS/PowerInfer/assets/154514502/6736468e-8c65-4da7-996b-d2e2afcecda3)
