### ISSUE TITLE
请问想要部署自己的模型

### ISSUE THREAD

**Issue by tanklandry** [SJTU-IPADS/PowerInfer#54]
应该还需要你们predictor训练的代码吧？还有ft转换relu的

**Comment by YixinSong-e** [comment]
是的，关于predictor训练和ft转换的代码都还在整理中。 predictor的训练可以参考[Dejavu](https://github.com/FMInference/DejaVu)，ft转换relu，根据SparseLLM Team的反馈，一个比较快能基本恢复模型能力的方法是直接将激活函数替换后，在你们模型预训练以及微调的语料中采样一部分直接进行训练即可，loss会迅速下降。

Yes, the code for predictor training and ft conversion is still being organized. The training of predictors can refer to [Dejavu](https://github.com/fminference/dejavu). According to the feedback from the SparseLLM Team, a fast and effective way to restore the model's ability is to directly replace the activation function and sample a portion of your pre trained and fine-tuning corpus for training, resulting in a rapid decrease in loss.
