### ISSUE TITLE
 No module named powerinfer, can ot split gpu

### ISSUE THREAD

**Issue by Gengchunsheng** [SJTU-IPADS/PowerInfer#55]
python3： No module named powerinfer
failed to generate gpu split..............

![Image 2](https://github.com/SJTU-IPADS/PowerInfer/assets/154514502/940c0590-1296-4029-b6c7-7f634a20a861)

**Comment by hodlen** [comment]
The cpp program of PoweInfer will invoke the `powerinfer` Python module for automatic FFN splitting. To make use of this feature, please ensure that you have run `pip install -r requirements.txt` as [README](https://github.com/SJTU-IPADS/PowerInfer#get-the-code) suggests. 

In case you are using any kind of Python virtual environment, please make sure the environment you have installed dependencies in is activated before the cpp program runs. 

If the problem still persists, please share your log and help us further investigate. Thanks!

**Comment by Gengchunsheng** [comment]
$pip install -r requirements.txt

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /mnt/PowerInfer/gguf-py
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

**Comment by Gengchunsheng** [comment]
This problem was solved when I reconfigured the Python environment.

**Comment by hodlen** [comment]
Glad to see it worked out 😄 Do you have a clue about the failure at first? I think it might help other users who have found a similar issue.

**Comment by Gengchunsheng** [comment]
> Glad to see it worked out 😄 Do you have a clue about the failure at first? I think it might help other users who have found a similar issue.

1. update the Python3.8 to  Python3.10
2. rebuild the cvxopt with glpk support.

But, the inference result is unacceptable when enabled the gpu split. See #77

**Comment by hodlen** [comment]
We have fixed Python dependency issues in #112. It should work on Python 3.8+ and pip 19.3+.
