### ISSUE TITLE
llama2中文 hf格式.bin  如何转换成PowerInfer格式?

### ISSUE THREAD

**Issue by Chenhuaqi6** [SJTU-IPADS/PowerInfer#56]

**Comment by lychee-2724540853** [comment]
好像中文Llama2的激活函数不是ReLU，PowerInfer不适用？PowerInfer是针对ReLU的？

**Comment by hodlen** [comment]
感谢你对PowerInfer的关注。目前，我们尚未支持基于Llama模型的各种变体。我们的系统目前支持使用ReLU激活函数的模型。虽然我们对原版的Llama 2模型进行了Fine-tune，使其可以使用ReLU激活函数，但这一支持并不包括Llama模型的所有变种。请参阅我们的[FAQs](https://github.com/SJTU-IPADS/PowerInfer#faqs)。

Thank you for your interest in PowerInfer. Currently, we do not support variants of the Llama model. Our system supports models using the ReLU activation function. Although we have fine-tuned the original Llama 2 model to use ReLU, this support does not extend to all variants of the Llama model. For more information, please refer to our [FAQs](https://github.com/SJTU-IPADS/PowerInfer#faqs).

**Comment by Chenhuaqi6** [comment]
好的 谢谢
