### ISSUE TITLE
请问你们是否有兴趣支持deepseek？

### ISSUE THREAD

**Issue by homosapien-lcy** [SJTU-IPADS/PowerInfer#67]
Deepseek-llm和Deepseek-coder效果也是很好的模型，而且是llama结构https://github.com/deepseek-ai/deepseek-coder/

**Comment by YixinSong-e** [comment]
我们非常有兴趣支持，也试图向deepseek团队进行了联系。

**Comment by tanklandry** [comment]
> 我们非常有兴趣支持，也试图向deepseek团队进行了联系，但目前没有回复。如果Deepseek团队对我们的工作也很感兴趣，希望能主动联系[yzmizeyu@sjtu.edu.cn](mailto:yzmizeyu@sjtu.edu.cn)

为啥要联系deepseek呢，我理解你们这边开源相关predictor和relu训练方案后，任意llama结构的模型都可以自行部署吧

**Comment by ZeyuMi** [comment]
我们已经和deepseek建立了联系，感谢大家的关心！
