### ISSUE TITLE
When I enable the gpu split,the inference result is unacceptable

### ISSUE THREAD

**Issue by Gengchunsheng** [SJTU-IPADS/PowerInfer#77]
When I enable the gpu split,the inference result is unacceptable.
![Image 3](https://github.com/SJTU-IPADS/PowerInfer/assets/154514502/5692029b-9449-47e8-8bf4-48e9e9dd9887)
![Image 2](https://github.com/SJTU-IPADS/PowerInfer/assets/154514502/64ff41cc-8127-4b32-895d-44482bb1c8bc)
![Image 4](https://github.com/SJTU-IPADS/PowerInfer/assets/154514502/38b99091-8097-43b9-a4a5-6f2ff9769703)
![Image 5](https://github.com/SJTU-IPADS/PowerInfer/assets/154514502/5dd4c3b3-a7d0-4b27-aea8-d15370c4a1bd)

**Comment by YixinSong-e** [comment]
Thank you for your feedback. Currently, we have received a bug issue with the GPU split sometimes not working properly, and we are investigating it.

**Comment by hodlen** [comment]
This is certainly a bug that deserves special attention. If you don't mind, we would greatly appreciate your help in troubleshooting it!

Could you please share the GPU index file generated during this error? It should be located in the same directory as the model, named "[model_name].generated.gpuidx". This file contains no private data and will greatly assist us in reproducing and resolving the issue on our end. Thank you!

**Comment by Gengchunsheng** [comment]
> This is certainly a bug that deserves special attention. If you don't mind, we would greatly appreciate your help in troubleshooting it!
> 
> Could you please share the GPU index file generated during this error? It should be located in the same directory as the model, named "[model_name].generated.gpuidx". This file contains no private data and will greatly assist us in reproducing and resolving the issue on our end. Thank you!

[Uploading falcon-40b-relu.q4.powerinfer.gguf.generated.zip…]()
[Uploading llama-70b-relu.q4.powerinfer.gguf.generated.zip…]()

**Comment by Gengchunsheng** [comment]
> This is certainly a bug that deserves special attention. If you don't mind, we would greatly appreciate your help in troubleshooting it!
> 
> Could you please share the GPU index file generated during this error? It should be located in the same directory as the model, named "[model_name].generated.gpuidx". This file contains no private data and will greatly assist us in reproducing and resolving the issue on our end. Thank you!

[falcon-40b-relu.q4.powerinfer.gguf.generated.zip](https://github.com/SJTU-IPADS/PowerInfer/files/13774594/falcon-40b-relu.q4.powerinfer.gguf.generated.zip)
[llama-70b-relu.q4.powerinfer.gguf.generated.zip](https://github.com/SJTU-IPADS/PowerInfer/files/13774595/llama-70b-relu.q4.powerinfer.gguf.generated.zip)

**Comment by hodlen** [comment]
HUGE thanks for your cooperation! We will try to reproduce the bug with them and keep you updated!

**Comment by Gengchunsheng** [comment]
> @Gengchunsheng Would you mind re-testing on our most recent commit and see if there is a difference? We fixed a crucial bug under INT4 inference that I believe is closely related to this issue.
> 
> Please **don't** run with `--reset-gpu-index` so the program uses the previously generated GPU index file.

I git  pull the project and rebuilt it, the running results look normal now.

![Image 8](https://github.com/SJTU-IPADS/PowerInfer/assets/154514502/57a946b7-93f7-4acc-8ea0-b78fe9608b82)
