### ISSUE TITLE
pip install -r requirements 提示 ./gguf-py not installable

### ISSUE THREAD

**Issue by jqliu42** [SJTU-IPADS/PowerInfer#78]
您好，请问在执行pip intall -r requirements.txt时，出现以下错误，请问如何解决？
![image](https://github.com/SJTU-IPADS/PowerInfer/assets/47267868/e05124c2-2e78-41dc-9577-bfdc0ff835dd)

**Comment by Gengchunsheng** [comment]
看看你的python版本，我遇到这个错误提示，是通过把python3.8升级到python3.10 解决的。
我也不懂python，查资料了解到setup.py 似乎是老版本python程序配置启动脚本，新版本支持pyproject.toml。

**Comment by hodlen** [comment]
谢谢 @Gengchunsheng 的建议，请尝试在Python 3.10以上的环境重新安装。我们会找时间确定项目中的Python模块对Python/pip的最低版本要求，并且更新到README中。

以下是我们开发环境中的Python和PIP版本，不低于此版本应当可以顺利安装：
* Python: 3.11.4
* pip: 23.0.1

欢迎尝试并反馈你的结果，以更好地帮助出现类似问题的人，谢谢。

===

Thanks for @Gengchunsheng‘s suggestion! Please try reinstalling in an environment with Python 3.10 or higher. We will allocate time to confirm the minimum version requirements for our Python module for both Python and pip, and update this information in the README.

Below are the versions of Python and pip in our development environment; versions not lower than these should allow for a smooth installation:

* Python: 3.11.4
* pip: 23.0.1

We welcome you to try this and share your results. Your feedback will help us better assist others facing similar issues. Thank you.

**Comment by hodlen** [comment]
我们在#112中修复了Python依赖问题。它应该适用于Python 3.8+和pip 19.3+。
---

We have fixed Python dependency issues in #112. It should work on Python 3.8+ and pip 19.3+.
