### ISSUE TITLE
我不懂编程

### ISSUE THREAD

**Issue by dyt06** [SJTU-IPADS/PowerInfer#79]
也不会编译c++程序，请问可否提供能直接运行的exe，cmd窗口下的就行。

**Comment by ZeyuMi** [comment]
欢迎使用我们的在线demo版本！在这个demo，我们已经搭建好了使用4090 GPU服务的falcon-40B的模型

You can try our online demo version! In this demo, we have deployed a model of the falcon-40B using the 4090 GPU. https://powerinfer-gradio.vercel.app/

**Comment by hodlen** [comment]
如果需要进一步的帮助，请重新开放此issue。

---

Feel free to reopen this issue for further assistance.
