### ISSUE TITLE
Windows CPU/GPU support

### ISSUE THREAD

**Issue by hodlen** [SJTU-IPADS/PowerInfer#86]
It requires modifying a series of POSIX API calls that are supported by MSVC to build PowerInfer on Windows under CPU inference and hybrid inference mode, including:
* Atomic operations in `stdatomic.h`;
* File system APIs such as `dirname`;
* `system` call also requires testing to ensure Python is running in the correct path and inherits all environment variables.

Related PR: 
~~#73 for CPU support~~ (closed)
#114 for CPU/GPU support

**Comment by 18635191739** [comment]
can windows use powerinfer now?

**Comment by hodlen** [comment]
Experimentally supported Windows on #114 now. We will spend some time to optimize inference performance under hybrid (CPU + GPU) inference and then merge it.
