### ISSUE TITLE
How to convert llama family model to powerinfer.gguf?

### ISSUE THREAD

**Issue by Mokuroh0924** [SJTU-IPADS/PowerInfer#94]
If I want to use the llama-based Chinese-alpaca-2-13b model, how should I convert it to powerinfer.gguf format?

**Comment by hodlen** [comment]
Thanks for your interest, but we only support ReLU-based models for now. 

Please kindly refer to our [FAQs](https://github.com/SJTU-IPADS/PowerInfer#faqs) and discussions from previous issues, including: 
* #56
* #32 
* #17
